version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BirthQuery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  fastapi-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
