version: "3"

services:

    frontend:
        image: birth_query_network-frontend:latest
        env_file:
            - ./activate.sh
        ports:
            - "9000:9000"
        networks:
            # connected to
            - frontend-network
            - backend-network

    backend:
        image: birth_query_network-backend:latest
        env_file:
            - ./activate.sh
        command:
            # initizalizing our server from sh
            - /bin/sh
            - "-c"
            - python main.py --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"
        networks:
            # connected to
            - frontend-network
            - backend-network

    db:
        image: postgres:14
        container_name: bq-database-c
        env_file:
            - ./activate.sh
        ports:
            - "5437:5432"
        networks:
            # connected to
            - backend-network


# docker networks, for our containers to
# communicate and share data each other
networks:
    backend-network:
        driver: bridge
    frontend-network:
        driver: bridge
