version: '3'

services:

  backend:
    command:
      -  /bin/sh
      -  "-c"
      -  cp /birthquery-backend /birthquery-backend
      -  cd /birthquery-backend && python3 main.py
      
   container_name: birthquery-backend
   build:
     context: ./birthquery-backend
     dockerfile: Dockerfile
   volumes:
     -  .:/code/backend/
   ports:
     -  "8000:8000"
   depends_on:
     -  db
   networks:
     -  backend
  
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: BirthQuery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      -  backend
      
networks:
    backend:
        driver: bridge
