version: "3"

services:

    frontend:
        container_name: bq-frontend-c
        # restart: always
        env_file:
            - ./secrets.sh
        build:
            # where is our build starting from and its Dockerfile
            context: ./birthquery-frontend
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        networks:
            # connected to
            - frontend-network
            - backend-network

    backend:
        container_name: bq-backend-c
        # restart: always
        env_file:
            - ./secrets.sh
        command:
            # initizalizing our server from sh
            - /bin/sh
            - "-c"
            - python main.py --host 0.0.0.0 --port 8000
        build:
            # where is our build starting from and its Dockerfile
            context: ./birthquery-backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        networks:
            # connected to
            - frontend-network
            - backend-network

    database:
        container_name: bq-database-c
        # image we us are using as our base
        # image: postgres:14
        # restart: always
        env_file:
            - ./secrets.sh
        build:
            # where is our build starting from and its Dockerfile
            context: ./
            dockerfile: Dockerfile.db
        ports:
            - "5437:5432"
        networks:
            # connected to
            - backend-network

# docker networks, for our containers to
# communicate and share data each other
networks:
    backend-network:
        driver: bridge
    frontend-network:
        driver: bridge
