# fly.toml app configuration file generated for long-leaf-1490 on 2023-09-03T22:50:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-leaf-1490"
primary_region = "ord"

[env]
  REACT_APP_API_URL_DEV="http://localhost:8000"
  REACT_APP_API_URL_PROD="https://lively-darkness-2264.fly.dev/"

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
